# Generated by Django 5.2.17 on 2026-09-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed', '-datetime']},
        ),
    ]
